function target = build_model(referenceFile)
root = fileparts(mfilename("fullpath"));
addpath(root);
if nargin < 1
    referenceFile = fullfile(root, "..", "results", "cca_contract", ...
        "cca_reference.csv");
end

config = simulation.nmpcSimulationConfig(simulation.nmpcConfig());
reference = read_reference(referenceFile, config.dt);
[ccaInput, ~] = pack_reference(reference, config);
initialState = reference(1, 2:7)';
assignin("base", "ccaInput", ccaInput);
assignin("base", "robot", robot_parameters());

model = "cca_nmpc_closed_loop";
target = fullfile(root, model + ".slx");
if bdIsLoaded(model)
    close_system(model, 0);
end
if isfile(target)
    delete(target);
end

new_system(model);
set_param(model, ...
    "SolverType", "Fixed-step", ...
    "Solver", "FixedStepDiscrete", ...
    "FixedStep", num2str(config.dt, 16), ...
    "StopTime", num2str(ccaInput(end, 1), 16), ...
    "SignalLogging", "on", ...
    "Location", [30, 30, 1900, 980]);

add_block("simulink/Sources/From Workspace", model + "/CCA local path", ...
    "VariableName", "ccaInput", ...
    "Interpolate", "on", ...
    "OutputAfterFinalValue", "Holding final value", ...
    "Position", [30, 180, 170, 220]);
add_chart(model + "/Current reference", [215, 180, 330, 220], [ ...
    "function output = select(value)", ...
    "output = value(1:6);", ...
    "end"]);
add_block("simulink/Math Operations/Sum", model + "/Tracking error", ...
    "Inputs", "+-", "Position", [380, 190, 420, 230]);
add_block("simulink/Sources/Clock", model + "/Time", ...
    "Position", [30, 310, 70, 340]);
add_block("simulink/Signal Routing/Mux", model + "/Controller input", ...
    "Inputs", "4", "DisplayOption", "bar", ...
    "Position", [455, 105, 465, 300]);
add_chart(model + "/NMPC Lyapunov", [510, 180, 690, 230], [ ...
    "function output = control(value)", ...
    "coder.extrinsic('simulation.simulinkNmpcStep');", ...
    "output = zeros(12,1);", ...
    "output = simulation.simulinkNmpcStep(value);", ...
    "end"]);
add_block("simulink/Signal Routing/Demux", model + "/Controller outputs", ...
    "Outputs", "[3 9]", "Position", [735, 170, 740, 245]);
add_subsystem_plant(model + "/Mecanum plant", initialState, config.dt);
add_block("simulink/Sources/Constant", model + "/Constant load", ...
    "Value", mat2str(config.loadBodyAcceleration, 16), ...
    "Position", [875, 300, 1010, 335]);
add_subsystem_estimator(model + "/Sensors and Kalman", ...
    initialState, config.dt);
add_block("simulink/Discrete/Unit Delay", model + "/Estimate feedback", ...
    "InitialCondition", mat2str(initialState, 16), ...
    "SampleTime", num2str(config.dt, 16), ...
    "Position", [1310, 120, 1360, 155]);

add_subsystem_monitoring(model + "/Monitoring scopes", [1150, 380, 1440, 585]);

add_line(model, "CCA local path/1", "Current reference/1", ...
    "autorouting", "on");
add_line(model, "CCA local path/1", "Controller input/2", ...
    "autorouting", "on");
add_line(model, "Current reference/1", "Tracking error/2", ...
    "autorouting", "on");
add_line(model, "Sensors and Kalman/1", "Estimate feedback/1", ...
    "autorouting", "on");
add_line(model, "Estimate feedback/1", "Tracking error/1", ...
    "autorouting", "on");
add_line(model, "Estimate feedback/1", "Controller input/1", ...
    "autorouting", "on");
add_line(model, "Tracking error/1", "Controller input/3", ...
    "autorouting", "on");
add_line(model, "Time/1", "Controller input/4", ...
    "autorouting", "on");
add_line(model, "Controller input/1", "NMPC Lyapunov/1", ...
    "autorouting", "on");
add_line(model, "NMPC Lyapunov/1", "Controller outputs/1", ...
    "autorouting", "on");
add_line(model, "Controller outputs/1", "Mecanum plant/1", ...
    "autorouting", "on");
add_line(model, "Constant load/1", "Mecanum plant/2", ...
    "autorouting", "on");
add_line(model, "Mecanum plant/1", "Sensors and Kalman/1", ...
    "autorouting", "on");
add_line(model, "Time/1", "Sensors and Kalman/3", ...
    "autorouting", "on");
add_line(model, "Controller outputs/1", "Sensors and Kalman/2", ...
    "autorouting", "on");

add_line(model, "Mecanum plant/1", "Monitoring scopes/1", ...
    "autorouting", "on");
add_line(model, "Current reference/1", "Monitoring scopes/2", ...
    "autorouting", "on");
add_line(model, "Tracking error/1", "Monitoring scopes/3", ...
    "autorouting", "on");
add_line(model, "Sensors and Kalman/3", "Monitoring scopes/4", ...
    "autorouting", "on");
add_line(model, "Controller outputs/2", "Monitoring scopes/5", ...
    "autorouting", "on");
add_line(model, "Controller outputs/1", "Monitoring scopes/6", ...
    "autorouting", "on");
add_line(model, "Sensors and Kalman/1", "Monitoring scopes/7", ...
    "autorouting", "on");

set_param(model, "ZoomFactor", "FitSystem");
save_system(model, target);
close_system(model, 0);
end

function add_subsystem_plant(path, initialState, dt)
add_block("simulink/Ports & Subsystems/Subsystem", path, ...
    "Position", [875, 165, 1045, 245]);
Simulink.SubSystem.deleteContents(path);
add_block("simulink/Ports & Subsystems/In1", path + "/Command u", ...
    "Port", "1", "Position", [25, 45, 55, 60]);
add_block("simulink/Ports & Subsystems/In1", path + "/Load d", ...
    "Port", "2", "Position", [25, 155, 55, 170]);
add_block("simulink/Ports & Subsystems/Out1", path + "/State X", ...
    "Port", "1", "Position", [555, 100, 585, 115]);
add_block("simulink/Discrete/Unit Delay", path + "/State memory", ...
    "InitialCondition", mat2str(initialState, 16), ...
    "SampleTime", num2str(dt, 16), "Position", [470, 90, 520, 125]);
add_block("simulink/Signal Routing/Mux", path + "/Dynamics input", ...
    "Inputs", "3", "Position", [115, 105, 120, 190]);
add_block("simulink/Signal Routing/Mux", path + "/Update input", ...
    "Inputs", "3", "Position", [360, 90, 365, 200]);
add_chart(path + "/Kinematics eta_dot", [155, 20, 290, 65], [ ...
    "function output = kinematics_block(value)", ...
    "coder.extrinsic('kinematics');", ...
    "output = zeros(3,1);", ...
    "state = value(1:6);", ...
    "output = kinematics(state, state(4:6), 'world');", ...
    "end"]);
add_chart(path + "/Dynamics dv", [155, 225, 290, 270], [ ...
    "function output = dynamics_block(value)", ...
    "coder.extrinsic('dynamics','robot_parameters');", ...
    "output = zeros(3,1);", ...
    "p = robot_parameters();", ...
    "output = dynamics(value(1:6), value(7:9), value(10:12), p);", ...
    "end"]);
add_chart(path + "/State update", [390, 170, 520, 220], [ ...
    "function output = update(value)", ...
    "coder.extrinsic('wrap_angle');", ...
    "output = value(1:6) + " + num2str(dt, 16) + ...
        " * [value(7:9); value(10:12)];", ...
    "output(3) = wrap_angle(output(3));", ...
    "end"]);
add_line(path, "Command u/1", "Dynamics input/2", ...
    "autorouting", "on");
add_line(path, "Load d/1", "Dynamics input/3", "autorouting", "on");
add_line(path, "State memory/1", "Kinematics eta_dot/1", ...
    "autorouting", "on");
add_line(path, "State memory/1", "Dynamics input/1", ...
    "autorouting", "on");
add_line(path, "Dynamics input/1", "Dynamics dv/1", ...
    "autorouting", "on");
add_line(path, "State memory/1", "Update input/1", ...
    "autorouting", "on");
add_line(path, "Kinematics eta_dot/1", "Update input/2", ...
    "autorouting", "on");
add_line(path, "Dynamics dv/1", "Update input/3", ...
    "autorouting", "on");
add_line(path, "Update input/1", "State update/1", ...
    "autorouting", "on");
add_line(path, "State update/1", "State memory/1", ...
    "autorouting", "on");
add_line(path, "State memory/1", "State X/1", "autorouting", "on");
end

function add_subsystem_estimator(path, initialState, dt)
add_block("simulink/Ports & Subsystems/Subsystem", path, ...
    "Position", [1090, 165, 1270, 265]);
Simulink.SubSystem.deleteContents(path);
add_block("simulink/Ports & Subsystems/In1", path + "/True state", ...
    "Port", "1", "Position", [25, 35, 55, 50]);
add_block("simulink/Ports & Subsystems/In1", path + "/Command", ...
    "Port", "2", "Position", [25, 110, 55, 125]);
add_block("simulink/Ports & Subsystems/In1", path + "/Time", ...
    "Port", "3", "Position", [25, 185, 55, 200]);
add_block("simulink/Ports & Subsystems/Out1", path + "/Estimate", ...
    "Port", "1", "Position", [560, 35, 590, 50]);
add_block("simulink/Ports & Subsystems/Out1", path + "/Measurement", ...
    "Port", "2", "Position", [560, 95, 590, 110]);
add_block("simulink/Ports & Subsystems/Out1", path + "/Innovation", ...
    "Port", "3", "Position", [560, 155, 590, 170]);
add_block("simulink/Ports & Subsystems/Out1", path + "/Covariance", ...
    "Port", "4", "Position", [560, 215, 590, 230]);
add_block("simulink/Discrete/Unit Delay", path + "/Estimate memory", ...
    "InitialCondition", mat2str(initialState, 16), ...
    "SampleTime", num2str(dt, 16), "Position", [390, 30, 440, 65]);
add_block("simulink/Signal Routing/Mux", path + "/Sensor input", ...
    "Inputs", "2", "Position", [105, 25, 110, 90]);
add_block("simulink/Signal Routing/Mux", path + "/EKF input", ...
    "Inputs", "4", "Position", [235, 20, 240, 185]);
add_chart(path + "/Measurement z", [135, 45, 225, 90], [ ...
    "function output = measure(value)", ...
    "coder.extrinsic('sensor_model','robot_parameters');", ...
    "output = zeros(6,1);", ...
    "output = sensor_model(value(1:6), value(7), robot_parameters());", ...
    "end"]);
add_chart(path + "/Kalman filter", [270, 85, 375, 140], [ ...
    "function output = filter(value)", ...
    "coder.extrinsic('simulation.simulinkEkfStep');", ...
    "output = zeros(19,1);", ...
    "output = simulation.simulinkEkfStep(value);", ...
    "end"]);
add_chart(path + "/Estimated state", [450, 20, 525, 50], [ ...
    "function output = state(value)", ...
    "output = value(1:6);", ...
    "end"]);
add_chart(path + "/Innovation vector", [450, 80, 525, 110], [ ...
    "function output = innovation(value)", ...
    "output = value(7:12);", ...
    "end"]);
add_chart(path + "/Covariance diagonal", [450, 140, 525, 170], [ ...
    "function output = covariance(value)", ...
    "output = value(13:18);", ...
    "end"]);
add_line(path, "True state/1", "Sensor input/1", "autorouting", "on");
add_line(path, "Time/1", "Sensor input/2", "autorouting", "on");
add_line(path, "Sensor input/1", "Measurement z/1", "autorouting", "on");
add_line(path, "Measurement z/1", "EKF input/2", "autorouting", "on");
add_line(path, "Estimate memory/1", "EKF input/1", "autorouting", "on");
add_line(path, "Command/1", "EKF input/3", "autorouting", "on");
add_line(path, "Time/1", "EKF input/4", "autorouting", "on");
add_line(path, "EKF input/1", "Kalman filter/1", "autorouting", "on");
add_line(path, "Kalman filter/1", "Estimated state/1", ...
    "autorouting", "on");
add_line(path, "Kalman filter/1", "Innovation vector/1", ...
    "autorouting", "on");
add_line(path, "Kalman filter/1", "Covariance diagonal/1", ...
    "autorouting", "on");
add_line(path, "Estimated state/1", "Estimate memory/1", ...
    "autorouting", "on");
add_line(path, "Estimated state/1", "Estimate/1", "autorouting", "on");
add_line(path, "Measurement z/1", "Measurement/1", ...
    "autorouting", "on");
add_line(path, "Innovation vector/1", "Innovation/1", ...
    "autorouting", "on");
add_line(path, "Covariance diagonal/1", "Covariance/1", ...
    "autorouting", "on");
end

function add_subsystem_monitoring(path, position)
add_block("simulink/Ports & Subsystems/Subsystem", path, ...
    "Position", position);
Simulink.SubSystem.deleteContents(path);
names = ["True state"; "Reference"; "Tracking error"; ...
    "Innovation"; "Lyapunov data"; "Command"; "Estimate"];
for index = 1:numel(names)
    add_block("simulink/Ports & Subsystems/In1", path + "/" + names(index), ...
        "Port", num2str(index), ...
        "Position", [25, 25 + 38 * (index - 1), 55, 40 + 38 * (index - 1)]);
end
add_block("simulink/Signal Routing/Demux", path + "/True parts", ...
    "Outputs", "[3 3]", "Position", [100, 20, 105, 80]);
add_block("simulink/Signal Routing/Demux", path + "/Reference parts", ...
    "Outputs", "[3 3]", "Position", [100, 105, 105, 165]);
add_chart(path + "/True XY", [135, 180, 210, 215], [ ...
    "function output = xy(value)", ...
    "output = value(1:2);", ...
    "end"]);
add_chart(path + "/Reference XY", [135, 230, 210, 265], [ ...
    "function output = xy(value)", ...
    "output = value(1:2);", ...
    "end"]);
add_scope(path + "/Position", 2, [240, 20, 380, 75]);
add_scope(path + "/Velocity", 2, [400, 20, 540, 75]);
add_scope(path + "/Trajectory", 2, [560, 20, 700, 75]);
add_scope(path + "/Tracking error scope", 1, [240, 105, 380, 160]);
add_scope(path + "/Kalman innovation scope", 1, [400, 105, 540, 160]);
add_scope(path + "/Lyapunov scope", 1, [560, 105, 700, 160]);
add_workspace_sink(path, "/True state log", "state_truth_log", ...
    [240, 190, 350, 220]);
add_workspace_sink(path, "/Estimated state log", "state_estimate_log", ...
    [360, 190, 480, 220]);
add_workspace_sink(path, "/Reference log", "reference_log", ...
    [490, 190, 600, 220]);
add_workspace_sink(path, "/Command log", "command_log", ...
    [610, 190, 720, 220]);
add_line(path, "True state/1", "True parts/1", "autorouting", "on");
add_line(path, "Reference/1", "Reference parts/1", "autorouting", "on");
add_line(path, "True parts/1", "Position/1", "autorouting", "on");
add_line(path, "Reference parts/1", "Position/2", "autorouting", "on");
add_line(path, "True parts/2", "Velocity/1", "autorouting", "on");
add_line(path, "Reference parts/2", "Velocity/2", "autorouting", "on");
add_line(path, "True state/1", "True XY/1", "autorouting", "on");
add_line(path, "Reference/1", "Reference XY/1", "autorouting", "on");
add_line(path, "True XY/1", "Trajectory/1", "autorouting", "on");
add_line(path, "Reference XY/1", "Trajectory/2", "autorouting", "on");
add_line(path, "Tracking error/1", "Tracking error scope/1", ...
    "autorouting", "on");
add_line(path, "Innovation/1", "Kalman innovation scope/1", ...
    "autorouting", "on");
add_line(path, "Lyapunov data/1", "Lyapunov scope/1", ...
    "autorouting", "on");
add_line(path, "True state/1", "True state log/1", "autorouting", "on");
add_line(path, "Reference/1", "Reference log/1", "autorouting", "on");
add_line(path, "Command/1", "Command log/1", "autorouting", "on");
add_line(path, "Estimate/1", "Estimated state log/1", ...
    "autorouting", "on");
end

function add_chart(path, position, lines)
add_block("simulink/User-Defined Functions/MATLAB Function", path, ...
    "Position", position);
chart = find(sfroot, "-isa", "Stateflow.EMChart", "Path", path);
chart.Script = strjoin(lines, newline);
end

function add_scope(path, ports, position)
add_block("simulink/Sinks/Scope", path, ...
    "NumInputPorts", num2str(ports), ...
    "OpenAtSimulationStart", "off", "Position", position);
end

function add_workspace_sink(model, name, variable, position)
add_block("simulink/Sinks/To Workspace", model + name, ...
    "VariableName", variable, "SaveFormat", "Timeseries", ...
    "Position", position);
end

function reference = read_reference(path, dt)
if ~isfile(path)
    error("build_model:missingReference", "Reference is missing: %s", path);
end
raw = readmatrix(path, "NumHeaderLines", 1);
if size(raw, 2) ~= 7 || size(raw, 1) < 2 || any(~isfinite(raw), "all")
    error("build_model:invalidReference", "Reference needs seven columns");
end
if any(diff(raw(:, 1)) <= 0)
    error("build_model:time", "Reference time must increase");
end
if abs(raw(1, 1)) > 1.0e-12
    raw(:, 1) = raw(:, 1) - raw(1, 1);
end
if any(abs(diff(raw(:, 1)) - dt) > 1.0e-8)
    error("build_model:sample", "Reference sample time must equal dt");
end
reference = raw;
end

function [packed, width] = pack_reference(reference, config)
horizon = config.horizon;
width = 6 * (horizon + 1) + 3 * horizon;
packed = zeros(size(reference, 1), width + 1);
for row = 1:size(reference, 1)
    indices = min(row:(row + horizon), size(reference, 1));
    states = reference(indices, 2:7)';
    alpha = min(1, config.dt / config.velocityTimeConstant);
    currentVelocity = reference(indices(1:end - 1), 5:7)';
    nextVelocity = reference(indices(2:end), 5:7)';
    commands = currentVelocity + (nextVelocity - currentVelocity) / alpha;
    packed(row, :) = [reference(row, 1), states(:)', commands(:)'];
end
end
