classdef nmpc_controller
    methods (Static)
        function result = solve(state, reference, config, initialCommands)
            started = tic;
            config = nmpc_controller.withDefaults(config);
            horizon = config.horizon;
            terminal = nmpc_controller.terminalDesign( ...
                reference.states(:, end), config);
            if config.controllerMode == "nominal_nmpc"
                config.P = zeros(6);
                config.terminalRho = inf;
            else
                config.P = terminal.P;
                config.terminalRho = terminal.rho;
            end
            config.Kf = terminal.K;
            if nargin < 4 || isempty(initialCommands)
                initialCommands = reference.commands;
            end
            if ~isequal(size(initialCommands), [3, horizon])
                error("nmpc:nmpc:guess", "Initial commands have invalid size")
            end
            initial = nmpc_controller.planStatus( ...
                state, initialCommands, reference, config);
            initialCertifiedOnTime = ...
                ~nmpc_controller.deadlineExceeded( ...
                    started, config.solveDeadlineMs);
            lower = repmat(config.commandLower(:), horizon, 1);
            upper = repmat(config.commandUpper(:), horizon, 1);
            objective = @(value) nmpc_controller.cost( ...
                state, reshape(value, 3, horizon), reference, config);
            constraints = @(value) nmpc_controller.constraints( ...
                state, reshape(value, 3, horizon), reference, config);
            if nmpc_controller.deadlineExceeded( ...
                    started, config.solveDeadlineMs)
                value = initialCommands(:);
                exitflag = -1;
                output = struct("iterations", 0);
                optimizerTimeMs = 0;
                optimizerAttempted = false;
            else
                outputFunction = @(value, values, phase) ...
                    nmpc_controller.deadlineOutput( ...
                        value, values, phase, started, ...
                        config.solveDeadlineMs);
                options = optimoptions("fmincon", ...
                    "Algorithm", "sqp", ...
                    "Display", "none", ...
                    "MaxIterations", config.maxIterations, ...
                    "MaxFunctionEvaluations", ...
                        config.maxFunctionEvaluations, ...
                    "ConstraintTolerance", config.constraintTolerance, ...
                    "OptimalityTolerance", config.optimalityTolerance, ...
                    "OutputFcn", outputFunction);
                optimizerStarted = tic;
                [value, ~, exitflag, output] = fmincon( ...
                    objective, initialCommands(:), [], [], [], [], ...
                    lower, upper, constraints, options);
                optimizerTimeMs = 1000 * toc(optimizerStarted);
                optimizerAttempted = true;
            end
            commands = reshape(value, 3, horizon);
            if optimizerAttempted
                candidate = nmpc_controller.planStatus( ...
                    state, commands, reference, config);
            else
                candidate = initial;
            end
            solveTimeMs = 1000 * toc(started);
            timedOut = nmpc_controller.deadlineExceeded( ...
                started, config.solveDeadlineMs);
            if timedOut && initialCertifiedOnTime && initial.feasible
                chosen = initial;
                selectionSource = "warm_start";
                usedFeasibleWarmStart = true;
            elseif timedOut
                chosen = nmpc_controller.deadlineStopPlan( ...
                    state, horizon);
                selectionSource = "deadline_stop";
                usedFeasibleWarmStart = false;
            else
                usedFeasibleWarmStart = initial.feasible && ...
                    (~candidate.feasible || candidate.cost > initial.cost);
                if usedFeasibleWarmStart
                    chosen = initial;
                    selectionSource = "warm_start";
                else
                    chosen = candidate;
                    selectionSource = "solver";
                end
            end
            terminalError = nmpc_controller.trackingError( ...
                chosen.states(:, end), reference.states(:, end));
            result = struct( ...
                "command", chosen.commands(:, 1), ...
                "commands", chosen.commands, ...
                "states", chosen.states, ...
                "cost", chosen.cost, ...
                "exitflag", exitflag, ...
                "iterations", output.iterations, ...
                "solveTimeMs", solveTimeMs, ...
                "optimizerTimeMs", optimizerTimeMs, ...
                "nominalBudgetMs", config.nominalSolveBudgetMs, ...
                "budgetOverrun", ...
                    solveTimeMs > config.nominalSolveBudgetMs, ...
                "timedOut", timedOut, ...
                "deadlineKind", "cooperative_iteration_boundary", ...
                "violation", chosen.violation, ...
                "controllerMode", config.controllerMode, ...
                "usedFeasibleWarmStart", usedFeasibleWarmStart, ...
                "selectionSource", selectionSource, ...
                "terminal", terminal, ...
                "terminalValue", terminalError' * config.P * terminalError, ...
                "feasible", chosen.feasible);
        end

        function value = cost(state, commands, reference, config)
            states = nmpc_controller.predictionStates( ...
                state, commands, reference, config);
            value = 0;
            for index = 1:config.horizon
                errorState = nmpc_controller.trackingError( ...
                    states(:, index), reference.states(:, index));
                errorCommand = commands(:, index) - reference.commands(:, index);
                value = value + errorState' * config.Q * errorState;
                value = value + errorCommand' * config.R * errorCommand;
            end
            terminalError = nmpc_controller.trackingError( ...
                states(:, end), reference.states(:, end));
            value = value + terminalError' * config.P * terminalError;
        end

        function [inequality, equality] = constraints( ...
                state, commands, reference, config)
            config = nmpc_controller.withDefaults(config);
            states = nmpc_controller.predictionStates( ...
                state, commands, reference, config);
            lowerCommand = repmat(config.commandLower(:), 1, config.horizon);
            upperCommand = repmat(config.commandUpper(:), 1, config.horizon);
            inequality = [lowerCommand(:) - commands(:); ...
                commands(:) - upperCommand(:)];
            for index = 1:config.horizon
                wheels = wheel_speeds( ...
                    commands(:, index), config.wheelRadius, ...
                    config.halfLength, config.halfWidth);
                inequality = [inequality; ...
                    wheels - config.wheelSpeedMax; ...
                    -wheels - config.wheelSpeedMax]; %#ok<AGROW>
            end
            boundedStates = states;
            if isfield(config, "stateLower")
                lowerBound = repmat( ...
                    config.stateLower(:), 1, config.horizon + 1);
                inequality = [inequality; lowerBound(:) - boundedStates(:)];
            end
            if isfield(config, "stateUpper")
                upperBound = repmat( ...
                    config.stateUpper(:), 1, config.horizon + 1);
                inequality = [inequality; boundedStates(:) - upperBound(:)];
            end
            if config.controllerMode ~= "nominal_nmpc"
                terminalError = nmpc_controller.trackingError( ...
                    states(:, end), reference.states(:, end));
                inequality = [inequality; ...
                    terminalError' * config.P * terminalError - config.terminalRho];
            end
            equality = [];
        end

        function errorState = trackingError(state, referenceState)
            errorState = state(:) - referenceState(:);
            errorState(3) = wrap_angle(errorState(3));
        end

        function reference = referenceFromPath(state, path, config)
            path = double(path);
            if size(path, 2) ~= 2 || size(path, 1) < 2
                error("nmpc:nmpc:path", "Path must have shape [M,2]")
            end
            keep = [true; vecnorm(diff(path), 2, 2) > eps];
            path = path(keep, :);
            if size(path, 1) < 2
                error("nmpc:nmpc:path", ...
                    "Path needs two distinct consecutive points")
            end
            distance = [0; cumsum(vecnorm(diff(path), 2, 2))];
            if distance(end) <= eps
                error("nmpc:nmpc:path", "Path length must be positive")
            end
            movingQuery = linspace(0, distance(end), config.horizon);
            query = [movingQuery, distance(end)];
            points = interp1(distance, path, query, "linear");
            if isfield(config, "alignYawToPath") && config.alignYawToPath
                tangent = [gradient(points(:, 1)), gradient(points(:, 2))];
                yaw = atan2(tangent(:, 2), tangent(:, 1));
            else
                yaw = repmat(state(3), config.horizon + 1, 1);
            end
            states = zeros(6, config.horizon + 1);
            commands = zeros(3, config.horizon);
            states(:, 1) = state(:);
            alpha = min(1, config.dt / config.velocityTimeConstant);
            for index = 1:config.horizon
                targetPose = [points(index + 1, :)'; yaw(index + 1)];
                poseDelta = targetPose - states(1:3, index);
                poseDelta(3) = wrap_angle(poseDelta(3));
                theta = states(3, index);
                transform = [cos(theta), -sin(theta), 0; ...
                             sin(theta),  cos(theta), 0; ...
                             0,           0,          1];
                nextVelocity = transform' * poseDelta / config.dt;
                commands(:, index) = states(4:6, index) + ...
                    (nextVelocity - states(4:6, index)) / alpha;
                states(:, index + 1) = position_step( ...
                    states(:, index), commands(:, index), config.dt, ...
                    config.velocityTimeConstant);
            end
            reference = struct("states", states, "commands", commands);
        end

        function residual = referenceResidual(reference, config)
            predicted = rollout_states( ...
                reference.states(:, 1), reference.commands, ...
                config.dt, config.velocityTimeConstant);
            delta = predicted - reference.states;
            delta(3, :) = atan2(sin(delta(3, :)), cos(delta(3, :)));
            residual = max(abs(delta), [], "all");
        end

        function gate = admit(state, newReference, fallbackPlan, config)
            gateStarted = tic;
            config = nmpc_controller.withDefaults(config);
            newCheck = nmpc_controller.referenceAdmissible(newReference, config);
            fallbackCheck = nmpc_controller.referenceAdmissible( ...
                fallbackPlan.reference, config);
            fallbackNow = nmpc_controller.evaluatePlan( ...
                state, fallbackPlan.commands, fallbackPlan.reference, config);
            spent = 1000 * toc(gateStarted);
            if isfinite(config.admissionDeadlineMs)
                remaining = max(0, config.admissionDeadlineMs - spent);
            else
                remaining = inf;
            end
            solveConfig = config;
            solveConfig.solveDeadlineMs = min( ...
                config.solveDeadlineMs, remaining);
            if newCheck.accepted && solveConfig.solveDeadlineMs > 0
                newResult = nmpc_controller.solve( ...
                    state, newReference, solveConfig, newReference.commands);
            else
                newResult = nmpc_controller.rejectedSolveResult(config);
                if newCheck.accepted
                    newResult.timedOut = true;
                    newResult.selectionSource = "admission_deadline";
                end
            end
            if newCheck.shapeValid && newCheck.finiteValues
                initialError = nmpc_controller.trackingError( ...
                    newReference.states(:, 1), state);
                initialMatch = norm(initialError, 2) <= ...
                    config.referenceTolerance;
                terminalError = nmpc_controller.trackingError( ...
                    newReference.states(:, end), ...
                    fallbackPlan.reference.states(:, end));
                terminalMatch = norm(terminalError, 2) <= ...
                    config.referenceTolerance;
            else
                initialMatch = false;
                terminalMatch = false;
            end
            fallbackInitialError = nmpc_controller.trackingError( ...
                fallbackPlan.reference.states(:, 1), state);
            fallbackInitialMatch = norm(fallbackInitialError, 2) <= ...
                config.referenceTolerance;
            fallbackUsable = fallbackCheck.accepted && ...
                fallbackNow.feasible && fallbackInitialMatch;
            gateTimeMs = 1000 * toc(gateStarted);
            deadlineAccepted = newCheck.accepted && ...
                ~newResult.timedOut && ...
                gateTimeMs <= config.admissionDeadlineMs;
            budgetOverrun = ...
                gateTimeMs > config.nominalSolveBudgetMs;
            accepted = newCheck.accepted && fallbackCheck.accepted && ...
                newResult.feasible && fallbackNow.feasible && ...
                initialMatch && fallbackInitialMatch && terminalMatch && ...
                deadlineAccepted;
            gate = struct( ...
                "accepted", accepted, ...
                "residual", newCheck.residual, ...
                "newCheck", newCheck, ...
                "fallbackCheck", fallbackCheck, ...
                "newResult", newResult, ...
                "fallbackPlan", fallbackPlan, ...
                "fallbackNow", fallbackNow, ...
                "initialMatch", initialMatch, ...
                "fallbackInitialMatch", fallbackInitialMatch, ...
                "fallbackUsable", fallbackUsable, ...
                "terminalMatch", terminalMatch, ...
                "deadlineAccepted", deadlineAccepted, ...
                "budgetOverrun", budgetOverrun, ...
                "gateTimeMs", gateTimeMs);
        end

        function gate = bootstrap(state, newReference, config)
            gateStarted = tic;
            config = nmpc_controller.withDefaults(config);
            state = double(state(:));
            stateValid = numel(state) == 6 && all(isfinite(state));
            newCheck = nmpc_controller.referenceAdmissible( ...
                newReference, config);
            initialMatch = false;
            atRest = false;
            if stateValid && newCheck.shapeValid && newCheck.finiteValues
                initialError = nmpc_controller.trackingError( ...
                    newReference.states(:, 1), state);
                initialMatch = norm(initialError, 2) <= ...
                    config.referenceTolerance;
                atRest = norm(state(4:6), 2) <= ...
                    config.bootstrapSpeedTolerance;
            end
            spent = 1000 * toc(gateStarted);
            if isfinite(config.admissionDeadlineMs)
                remaining = max(0, config.admissionDeadlineMs - spent);
            else
                remaining = inf;
            end
            solveConfig = config;
            solveConfig.solveDeadlineMs = min( ...
                config.solveDeadlineMs, remaining);
            if newCheck.accepted && initialMatch && atRest && ...
                    solveConfig.solveDeadlineMs > 0
                newResult = nmpc_controller.solve( ...
                    state, newReference, solveConfig, ...
                    newReference.commands);
            else
                newResult = nmpc_controller.rejectedSolveResult(config);
                if newCheck.accepted && initialMatch && atRest
                    newResult.timedOut = true;
                    newResult.selectionSource = "bootstrap_deadline";
                end
            end
            gateTimeMs = 1000 * toc(gateStarted);
            deadlineAccepted = newCheck.accepted && ...
                ~newResult.timedOut && ...
                gateTimeMs <= config.admissionDeadlineMs;
            budgetOverrun = ...
                gateTimeMs > config.nominalSolveBudgetMs;
            accepted = stateValid && atRest && newCheck.accepted && ...
                initialMatch && newResult.feasible && deadlineAccepted;
            gate = struct( ...
                "accepted", accepted, ...
                "newCheck", newCheck, ...
                "newResult", newResult, ...
                "stateValid", stateValid, ...
                "atRest", atRest, ...
                "initialMatch", initialMatch, ...
                "deadlineAccepted", deadlineAccepted, ...
                "budgetOverrun", budgetOverrun, ...
                "gateTimeMs", gateTimeMs);
        end

        function check = referenceAdmissible(reference, config)
            expectedStates = [6, config.horizon + 1];
            expectedCommands = [3, config.horizon];
            shapeValid = isstruct(reference) && ...
                isfield(reference, "states") && ...
                isfield(reference, "commands") && ...
                isequal(size(reference.states), expectedStates) && ...
                isequal(size(reference.commands), expectedCommands);
            finiteValues = shapeValid && ...
                all(isfinite(reference.states), "all") && ...
                all(isfinite(reference.commands), "all");
            if ~finiteValues
                check = struct( ...
                    "accepted", false, ...
                    "shapeValid", shapeValid, ...
                    "finiteValues", finiteValues, ...
                    "residual", inf, ...
                    "commandViolation", inf, ...
                    "wheelViolation", inf, ...
                    "stateViolation", inf, ...
                    "endSpeed", inf);
                return
            end
            residual = nmpc_controller.referenceResidual(reference, config);
            commandViolation = max([0; ...
                config.commandLower(:) - min(reference.commands, [], 2); ...
                max(reference.commands, [], 2) - config.commandUpper(:)]);
            wheelViolation = 0;
            for index = 1:config.horizon
                wheels = wheel_speeds( ...
                    reference.commands(:, index), config.wheelRadius, ...
                    config.halfLength, config.halfWidth);
                wheelViolation = max(wheelViolation, ...
                    max(abs(wheels)) - config.wheelSpeedMax);
            end
            stateViolation = 0;
            if isfield(config, "stateLower")
                stateViolation = max(stateViolation, max( ...
                    config.stateLower(:) - min(reference.states, [], 2)));
            end
            if isfield(config, "stateUpper")
                stateViolation = max(stateViolation, max( ...
                    max(reference.states, [], 2) - config.stateUpper(:)));
            end
            endSpeed = norm(reference.states(4:6, end), 2);
            accepted = residual <= config.referenceTolerance && ...
                commandViolation <= config.constraintTolerance && ...
                wheelViolation <= config.constraintTolerance && ...
                stateViolation <= config.constraintTolerance && ...
                endSpeed <= config.referenceEndSpeedTolerance;
            check = struct( ...
                "accepted", accepted, ...
                "shapeValid", shapeValid, ...
                "finiteValues", finiteValues, ...
                "residual", residual, ...
                "commandViolation", max(0, commandViolation), ...
                "wheelViolation", max(0, wheelViolation), ...
                "stateViolation", max(0, stateViolation), ...
                "endSpeed", endSpeed);
        end

        function shifted = shiftReference(reference)
            states = [reference.states(:, 2:end), reference.states(:, end)];
            commands = [reference.commands(:, 2:end), zeros(3, 1)];
            shifted = struct("states", states, "commands", commands);
        end

        function plan = shiftPlan(result, reference, config)
            config = nmpc_controller.withDefaults(config);
            if config.controllerMode ~= "terminal_nmpc"
                error("nmpc:nmpc:shift", ...
                    "Shift proof applies only to terminal NMPC")
            end
            shiftedReference = nmpc_controller.shiftReference(reference);
            commands = nmpc_controller.shiftedCommands(result, reference);
            state = result.states(:, 2);
            plan = nmpc_controller.evaluatePlan( ...
                state, commands, shiftedReference, config);
        end

        function plan = evaluatePlan(state, commands, reference, config)
            config = nmpc_controller.withDefaults(config);
            config.controllerMode = "terminal_nmpc";
            terminal = nmpc_controller.terminalDesign( ...
                reference.states(:, end), config);
            config.P = terminal.P;
            config.Kf = terminal.K;
            config.terminalRho = terminal.rho;
            status = nmpc_controller.planStatus( ...
                state, commands, reference, config);
            plan = struct( ...
                "state", state, ...
                "reference", reference, ...
                "commands", status.commands, ...
                "states", status.states, ...
                "cost", status.cost, ...
                "violation", status.violation, ...
                "terminal", terminal, ...
                "feasible", status.feasible);
        end

        function commands = shiftedCommands(result, reference)
            errorState = nmpc_controller.trackingError( ...
                result.states(:, end), reference.states(:, end));
            terminalCommand = result.terminal.K * errorState;
            commands = [result.commands(:, 2:end), terminalCommand];
        end

        function terminal = terminalDesign(terminalReference, config)
            reference = nmpc_controller.terminalState(terminalReference);
            symmetricQ = 0.5 * (config.Q + config.Q');
            symmetricR = 0.5 * (config.R + config.R');
            if min(eig(symmetricQ)) <= 0 || min(eig(symmetricR)) <= 0
                error("nmpc:nmpc:terminal", ...
                    "Terminal weights must be positive definite")
            end
            if any(config.commandLower(:) >= 0) || ...
                    any(config.commandUpper(:) <= 0)
                error("nmpc:nmpc:terminal", ...
                    "Zero command must be in the interior")
            end
            if config.terminalErrorLimits(3) >= pi
                error("nmpc:nmpc:terminal", ...
                    "Terminal yaw error must stay inside one angle chart")
            end
            if isfield(config, "stateLower") && ...
                    any(reference <= config.stateLower(:))
                error("nmpc:nmpc:terminal", ...
                    "Terminal state must be inside the lower state bound")
            end
            if isfield(config, "stateUpper") && ...
                    any(reference >= config.stateUpper(:))
                error("nmpc:nmpc:terminal", ...
                    "Terminal state must be inside the upper state bound")
            end
            alpha = min(1, config.dt / config.velocityTimeConstant);
            decay = 1 - alpha;
            [A, B] = state_jacobian( ...
                reference, zeros(3, 1), config.dt, ...
                config.velocityTimeConstant);
            controllabilityRank = rank(ctrb(A, B));
            if controllabilityRank < 6
                error("nmpc:nmpc:terminal", ...
                    "Terminal linearization is not controllable")
            end
            [gain, ~] = dlqr(A, B, config.Q, config.R);
            K = -gain;
            closedLoop = A + B * K;
            stage = config.Q + K' * config.R * K;
            P = dlyap(closedLoop', 2 * stage);
            P = 0.5 * (P + P');
            velocityMap = [zeros(3), decay * eye(3)] + alpha * K;
            remainderGain = config.dt * norm(velocityMap(1:2, :), 2);
            linearTerm = 2 * norm(closedLoop' * P, 2) * remainderGain;
            quadraticTerm = norm(P, 2) * remainderGain ^ 2;
            target = min(eig(stage));
            if quadraticTerm > eps
                radius = (-linearTerm + sqrt( ...
                    linearTerm ^ 2 + 4 * quadraticTerm * target)) / ...
                    (2 * quadraticTerm);
            elseif linearTerm > eps
                radius = target / linearTerm;
            else
                radius = inf;
            end
            inverseP = P \ eye(6);
            rhoLyapunov = min(eig(P)) * radius ^ 2;
            rho = min(config.terminalRhoMax, rhoLyapunov);
            for index = 1:6
                limit = config.terminalErrorLimits(index);
                rho = min(rho, limit ^ 2 / max(inverseP(index, index), eps));
            end
            stateMargin = inf(6, 1);
            if isfield(config, "stateLower")
                stateMargin = min(stateMargin, ...
                    reference - config.stateLower(:));
            end
            if isfield(config, "stateUpper")
                stateMargin = min(stateMargin, ...
                    config.stateUpper(:) - reference);
            end
            for index = 1:6
                if isfinite(stateMargin(index))
                    limit = max(0, stateMargin(index));
                    rho = min(rho, ...
                        limit ^ 2 / max(inverseP(index, index), eps));
                end
            end
            commandLimit = min(config.commandUpper(:), ...
                -config.commandLower(:));
            for index = 1:3
                value = K(index, :) * inverseP * K(index, :)';
                rho = min(rho, commandLimit(index) ^ 2 / max(value, eps));
            end
            mixer = zeros(4, 3);
            for index = 1:3
                basis = zeros(3, 1);
                basis(index) = 1;
                mixer(:, index) = wheel_speeds( ...
                    basis, config.wheelRadius, config.halfLength, ...
                    config.halfWidth);
            end
            wheelFeedback = mixer * K;
            for index = 1:4
                value = wheelFeedback(index, :) * inverseP * ...
                    wheelFeedback(index, :)';
                rho = min(rho, config.wheelSpeedMax ^ 2 / max(value, eps));
            end
            if ~(isfinite(rho) && rho > 0)
                error("nmpc:nmpc:terminal", ...
                    "Terminal set must have positive finite size")
            end
            terminal = struct( ...
                "A", A, ...
                "B", B, ...
                "K", K, ...
                "P", P, ...
                "rho", rho, ...
                "referenceState", reference, ...
                "stateMargin", stateMargin, ...
                "rhoLyapunov", rhoLyapunov, ...
                "remainderGain", remainderGain, ...
                "controllabilityRank", controllabilityRank, ...
                "spectralRadius", max(abs(eig(closedLoop))), ...
                "linearDecrease", min(eig(stage)));
        end

        function audit = terminalAudit(terminalReference, config)
            terminal = nmpc_controller.terminalDesign(terminalReference, config);
            factor = chol(terminal.P, "lower");
            directions = [eye(6), -eye(6), ...
                ones(6, 1) / sqrt(6), -ones(6, 1) / sqrt(6)];
            sampleIndex = 1:config.terminalAuditDirections;
            samples = sin((1:6)' * (sqrt(2) * sampleIndex + sqrt(3))) + ...
                cos((1:6)' * (sqrt(5) * sampleIndex + sqrt(7)));
            samples = samples ./ vecnorm(samples, 2, 1);
            directions = [directions, samples];
            fractions = [0.25, 0.50, 0.75, 1.00];
            reference = terminal.referenceState;
            minMargin = inf;
            maxRatio = 0;
            maxWheel = 0;
            maxCommandViolation = 0;
            for fraction = fractions
                for index = 1:size(directions, 2)
                    direction = directions(:, index);
                    direction = direction / norm(direction, 2);
                    errorState = sqrt(terminal.rho) * fraction * ...
                        (factor' \ direction);
                    command = terminal.K * errorState;
                    state = reference + errorState;
                    next = position_step( ...
                        state, command, config.dt, ...
                        config.velocityTimeConstant);
                    nextError = nmpc_controller.trackingError(next, reference);
                    value = errorState' * terminal.P * errorState;
                    nextValue = nextError' * terminal.P * nextError;
                    stage = errorState' * config.Q * errorState + ...
                        command' * config.R * command;
                    minMargin = min(minMargin, -(nextValue - value) - stage);
                    maxRatio = max(maxRatio, nextValue / terminal.rho);
                    wheels = wheel_speeds( ...
                        command, config.wheelRadius, config.halfLength, ...
                        config.halfWidth);
                    maxWheel = max(maxWheel, max(abs(wheels)));
                    commandViolation = max([0; ...
                        config.commandLower(:) - command; ...
                        command - config.commandUpper(:)]);
                    maxCommandViolation = max( ...
                        maxCommandViolation, commandViolation);
                end
            end
            passed = terminal.rho > 0 && terminal.spectralRadius < 1 && ...
                terminal.rho <= terminal.rhoLyapunov && ...
                minMargin >= -config.terminalAuditTolerance && ...
                maxRatio <= 1 + config.terminalAuditTolerance && ...
                maxCommandViolation <= config.constraintTolerance && ...
                maxWheel <= config.wheelSpeedMax + config.constraintTolerance;
            audit = struct( ...
                "passed", passed, ...
                "terminal", terminal, ...
                "minimumDecreaseMargin", minMargin, ...
                "maximumSuccessorRatio", maxRatio, ...
                "maximumCommandViolation", maxCommandViolation, ...
                "maximumWheelSpeed", maxWheel);
        end

        function status = planStatus(state, commands, reference, config)
            states = nmpc_controller.predictionStates( ...
                state, commands, reference, config);
            value = nmpc_controller.cost( ...
                state, commands, reference, config);
            [inequality, equality] = nmpc_controller.constraints( ...
                state, commands, reference, config);
            violation = max([0; inequality(:); abs(equality(:))]);
            finite = isfinite(value) && all(isfinite(commands), "all") && ...
                all(isfinite(states), "all") && isfinite(violation);
            status = struct( ...
                "commands", commands, ...
                "states", states, ...
                "cost", value, ...
                "violation", violation, ...
                "finite", finite, ...
                "feasible", finite && ...
                violation <= config.planAcceptanceTolerance);
        end

        function states = predictionStates(state, commands, reference, config)
            config = nmpc_controller.withDefaults(config);
            if config.controllerMode == "linear_mpc"
                states = nmpc_controller.linearRollout( ...
                    state, commands, reference, config);
            else
                states = rollout_states( ...
                    state, commands, config.dt, ...
                    config.velocityTimeConstant);
            end
        end

        function states = linearRollout(state, commands, reference, config)
            states = zeros(6, config.horizon + 1);
            states(:, 1) = state(:);
            errorState = nmpc_controller.trackingError( ...
                state, reference.states(:, 1));
            for index = 1:config.horizon
                [A, B] = state_jacobian( ...
                    reference.states(:, index), ...
                    reference.commands(:, index), config.dt, ...
                    config.velocityTimeConstant);
                commandError = commands(:, index) - ...
                    reference.commands(:, index);
                errorState = A * errorState + B * commandError;
                errorState(3) = wrap_angle(errorState(3));
                states(:, index + 1) = ...
                    reference.states(:, index + 1) + errorState;
                    states(3, index + 1) = wrap_angle( ...
                    states(3, index + 1));
            end
        end

        function reference = terminalState(value)
            if isscalar(value)
                reference = [0; 0; double(value); 0; 0; 0];
            else
                reference = double(value(:));
                if numel(reference) ~= 6
                    error("nmpc:nmpc:terminal", ...
                        "Terminal reference must be scalar yaw or six states")
                end
            end
            reference(3) = wrap_angle(reference(3));
            if norm(reference(4:6), 2) > 1.0e-10
                error("nmpc:nmpc:terminal", ...
                    "Terminal reference must be a rest equilibrium")
            end
        end

        function config = withDefaults(config)
            if ~isfield(config, "controllerMode")
                config.controllerMode = "terminal_nmpc";
            end
            if ~isfield(config, "planAcceptanceTolerance")
                config.planAcceptanceTolerance = 0;
            end
            if ~isfield(config, "solveDeadlineMs")
                config.solveDeadlineMs = 90;
            end
            if ~isfield(config, "admissionDeadlineMs")
                config.admissionDeadlineMs = 90;
            end
            if ~isfield(config, "nominalSolveBudgetMs")
                config.nominalSolveBudgetMs = 60;
            end
            if ~isfield(config, "bootstrapSpeedTolerance")
                config.bootstrapSpeedTolerance = 1.0e-8;
            end
            if ~isfield(config, "maxFunctionEvaluations")
                config.maxFunctionEvaluations = 5000;
            end
            nmpc_controller.validateDeadline( ...
                config.solveDeadlineMs, "solveDeadlineMs");
            nmpc_controller.validateDeadline( ...
                config.admissionDeadlineMs, "admissionDeadlineMs");
            nmpc_controller.validateDeadline( ...
                config.nominalSolveBudgetMs, "nominalSolveBudgetMs");
            if ~isfinite(config.nominalSolveBudgetMs)
                error("nmpc:nmpc:deadline", ...
                    "Nominal solve budget must be finite")
            end
            if ~isnumeric(config.bootstrapSpeedTolerance) || ...
                    ~isscalar(config.bootstrapSpeedTolerance) || ...
                    ~isfinite(config.bootstrapSpeedTolerance) || ...
                    config.bootstrapSpeedTolerance < 0
                error("nmpc:nmpc:bootstrap", ...
                    "Bootstrap speed tolerance must be nonnegative")
            end
            if ~isnumeric(config.maxFunctionEvaluations) || ...
                    ~isscalar(config.maxFunctionEvaluations) || ...
                    ~isfinite(config.maxFunctionEvaluations) || ...
                    config.maxFunctionEvaluations < 1 || ...
                    fix(config.maxFunctionEvaluations) ~= ...
                        config.maxFunctionEvaluations
                error("nmpc:nmpc:functionBudget", ...
                    "Max function evaluations must be a positive integer")
            end
        end

        function validateDeadline(value, name)
            valid = isnumeric(value) && isscalar(value) && ...
                isreal(value) && ~isnan(value) && value >= 0;
            if ~valid
                error("nmpc:nmpc:deadline", ...
                    "%s must be a nonnegative scalar or Inf", name)
            end
        end

        function stop = deadlineOutput(~, ~, ~, started, deadlineMs)
            stop = nmpc_controller.deadlineExceeded(started, deadlineMs);
        end

        function expired = deadlineExceeded(started, deadlineMs)
            expired = isfinite(deadlineMs) && ...
                1000 * toc(started) >= deadlineMs;
        end

        function result = rejectedSolveResult(config)
            result = struct( ...
                "command", zeros(3, 1), ...
                "commands", zeros(3, config.horizon), ...
                "states", nan(6, config.horizon + 1), ...
                "cost", inf, ...
                "exitflag", -2, ...
                "iterations", 0, ...
                "solveTimeMs", 0, ...
                "optimizerTimeMs", 0, ...
                "nominalBudgetMs", config.nominalSolveBudgetMs, ...
                "budgetOverrun", false, ...
                "timedOut", false, ...
                "deadlineKind", "cooperative_iteration_boundary", ...
                "violation", inf, ...
                "controllerMode", config.controllerMode, ...
                "usedFeasibleWarmStart", false, ...
                "selectionSource", "rejected_reference", ...
                "terminal", struct(), ...
                "terminalValue", inf, ...
                "feasible", false);
        end

        function plan = deadlineStopPlan(state, horizon)
            plan = struct( ...
                "commands", zeros(3, horizon), ...
                "states", repmat(state(:), 1, horizon + 1), ...
                "cost", inf, ...
                "violation", inf, ...
                "feasible", false);
        end

        function reference = stationaryReference(referenceState, config)
            target = referenceState(:);
            target(4:6) = 0;
            reference = struct( ...
                "states", repmat(target, 1, config.horizon + 1), ...
                "commands", zeros(3, config.horizon));
        end

        function command = terminalCommand(errorState, referenceCommand, config)
            command = referenceCommand(:) + config.Kf * errorState(:);
        end
    end
end
