classdef simulation
    methods (Static)
        function result = run()
            config = simulation.nmpcConfig();
            result = simulation.nonzeroClosedLoop(config);
            result.controllerMode = config.controllerMode;
            result.evidenceScope = "nmpc_lyapunov_only";
        end

        function config = nmpcConfig()
            robot = robot_parameters();
            config = struct( ...
                "dt", robot.dt, ...
                "velocityTimeConstant", robot.velocityTimeConstant, ...
                "horizon", 20, ...
                "controllerMode", "terminal_nmpc", ...
                "alignYawToPath", false, ...
                "Q", diag([20, 20, 8, 2, 2, 1]), ...
                "R", diag([0.4, 0.4, 0.2]), ...
                "commandLower", [-2.0; -2.0; -3.0], ...
                "commandUpper", [2.0; 2.0; 3.0], ...
                "wheelRadius", robot.wheelRadius, ...
                "halfLength", robot.halfLength, ...
                "halfWidth", robot.halfWidth, ...
                "wheelSpeedMax", 100.0, ...
                "loadBodyAcceleration", robot.loadBodyAcceleration, ...
                "sensorNoiseStd", robot.sensorNoiseStd, ...
                "sensorNoisePhase", robot.sensorNoisePhase, ...
                "ekfProcessNoiseStd", robot.ekfProcessNoiseStd, ...
                "ekfMeasurementNoiseStd", robot.ekfMeasurementNoiseStd, ...
                "ekfInitialCovariance", robot.ekfInitialCovariance, ...
                "terminalErrorLimits", ...
                    [0.20; 0.20; 0.20; 0.50; 0.50; 0.80], ...
                "terminalRhoMax", 0.04, ...
                "terminalAuditDirections", 128, ...
                "terminalAuditTolerance", 1.0e-9, ...
                "referenceTolerance", 1.0e-10, ...
                "referenceEndSpeedTolerance", 1.0e-10, ...
                "planAcceptanceTolerance", 0.0, ...
                "constraintTolerance", 1.0e-7, ...
                "optimalityTolerance", 1.0e-7, ...
                "maxIterations", 80, ...
                "maxFunctionEvaluations", 5000, ...
                "nominalSolveBudgetMs", 60, ...
                "solveDeadlineMs", 90, ...
                "admissionDeadlineMs", 90, ...
                "bootstrapSpeedTolerance", 1.0e-8);
        end

        function metrics = nonzeroClosedLoop(config)
            if nargin < 1
                config = simulation.nmpcConfig();
            end
            config = simulation.nmpcSimulationConfig(config);
            [reference, state, initialError] = ...
                simulation.nmpcSimulationCase(config);
            referenceCheck = nmpc_controller.referenceAdmissible( ...
                reference, config);
            assert(referenceCheck.accepted);
            terminal = nmpc_controller.terminalDesign( ...
                reference.states(:, end), config);
            warmCommands = simulation.feedbackWarmStart( ...
                state, reference, config);
            transitionCount = config.horizon;
            stateHistory = zeros(6, transitionCount + 1);
            referenceHistory = zeros(6, transitionCount + 1);
            errorHistory = zeros(6, transitionCount + 1);
            commandHistory = zeros(3, transitionCount);
            wheelHistory = zeros(4, transitionCount);
            selectedCost = zeros(1, transitionCount + 1);
            warmCost = zeros(1, transitionCount + 1);
            selectionResidual = zeros(1, transitionCount + 1);
            terminalRatio = zeros(1, transitionCount + 1);
            solveTime = zeros(1, transitionCount + 1);
            stageCost = zeros(1, transitionCount);
            shiftCost = zeros(1, transitionCount);
            shiftResidual = zeros(1, transitionCount);
            planViolation = zeros(1, transitionCount + 1);
            stateViolation = zeros(1, transitionCount + 1);
            commandViolation = zeros(1, transitionCount);
            wheelViolation = zeros(1, transitionCount);
            deadlineMiss = false(1, transitionCount + 1);
            for step = 1:transitionCount + 1
                check = nmpc_controller.referenceAdmissible( ...
                    reference, config);
                assert(check.accepted);
                warmStart = nmpc_controller.evaluatePlan( ...
                    state, warmCommands, reference, config);
                assert(warmStart.feasible);
                selected = nmpc_controller.solve( ...
                    state, reference, config, warmCommands);
                assert(selected.feasible);
                stateHistory(:, step) = state;
                referenceHistory(:, step) = reference.states(:, 1);
                errorHistory(:, step) = nmpc_controller.trackingError( ...
                    state, reference.states(:, 1));
                selectedCost(step) = selected.cost;
                warmCost(step) = warmStart.cost;
                selectionResidual(step) = selected.cost - warmStart.cost;
                terminalRatio(step) = ...
                    selected.terminalValue / selected.terminal.rho;
                solveTime(step) = selected.solveTimeMs;
                planViolation(step) = selected.violation;
                stateViolation(step) = max([0; ...
                    config.stateLower - state; ...
                    state - config.stateUpper]);
                deadlineMiss(step) = selected.timedOut;
                if step > transitionCount
                    break
                end
                command = selected.command;
                wheel = wheel_speeds( ...
                    command, config.wheelRadius, ...
                    config.halfLength, config.halfWidth);
                commandHistory(:, step) = command;
                wheelHistory(:, step) = wheel;
                commandViolation(step) = max([0; ...
                    config.commandLower - command; ...
                    command - config.commandUpper]);
                wheelViolation(step) = max(0, ...
                    max(abs(wheel)) - config.wheelSpeedMax);
                errorState = errorHistory(:, step);
                commandError = command - reference.commands(:, 1);
                stageCost(step) = ...
                    errorState' * config.Q * errorState + ...
                    commandError' * config.R * commandError;
                shifted = nmpc_controller.shiftPlan( ...
                    selected, reference, config);
                assert(shifted.feasible);
                shiftCost(step) = shifted.cost;
                shiftResidual(step) = ...
                    shifted.cost - selected.cost + stageCost(step);
                nextState = position_step( ...
                    state, command, config.dt, ...
                    config.velocityTimeConstant);
                assert(max(abs(nextState - ...
                    selected.states(:, 2))) <= 1.0e-12);
                state = nextState;
                reference = shifted.reference;
                warmCommands = shifted.commands;
            end
            lyapunovResidual = diff(selectedCost) + stageCost;
            costIncrease = diff(selectedCost);
            metrics = struct( ...
                "timeS", (0:transitionCount) * config.dt, ...
                "stateHistory", stateHistory, ...
                "referenceHistory", referenceHistory, ...
                "trackingErrorHistory", errorHistory, ...
                "appliedCommandHistory", commandHistory, ...
                "wheelSpeedHistory", wheelHistory, ...
                "selectedCostHistory", selectedCost, ...
                "warmStartCostHistory", warmCost, ...
                "stageCostHistory", stageCost, ...
                "shiftedCostHistory", shiftCost, ...
                "selectionResidualHistory", selectionResidual, ...
                "shiftResidualHistory", shiftResidual, ...
                "lyapunovResidualHistory", lyapunovResidual, ...
                "terminalRatioHistory", terminalRatio, ...
                "planViolationHistory", planViolation, ...
                "solveTimeHistoryMs", solveTime, ...
                "initialErrorNorm", norm(initialError, 2), ...
                "initialPositionErrorM", ...
                    norm(initialError(1:2), 2), ...
                "initialYawErrorRad", abs(initialError(3)), ...
                "initialVelocityErrorMps", ...
                    norm(initialError(4:5), 2), ...
                "initialYawRateErrorRadps", abs(initialError(6)), ...
                "initialTerminalRatio", ...
                    initialError' * terminal.P * initialError / ...
                    terminal.rho, ...
                "referenceResidual", referenceCheck.residual, ...
                "yawVariation", max(abs(referenceHistory(3, :) - ...
                    referenceHistory(3, 1))), ...
                "maximumSelectionResidual", ...
                    max(selectionResidual), ...
                "maximumShiftResidual", max(shiftResidual), ...
                "maximumLyapunovResidual", max(lyapunovResidual), ...
                "maximumCostIncrease", max(costIncrease), ...
                "maximumStateViolation", max(stateViolation), ...
                "maximumCommandViolation", max(commandViolation), ...
                "maximumWheelViolation", max(wheelViolation), ...
                "maximumPlanViolation", max(planViolation), ...
                "maximumTerminalRatio", max(terminalRatio), ...
                "peakCommandAbs", ...
                    max(abs(commandHistory), [], "all"), ...
                "peakWheelSpeedRadps", ...
                    max(abs(wheelHistory), [], "all"), ...
                "finalPositionErrorM", ...
                    norm(errorHistory(1:2, end), 2), ...
                "finalVelocityErrorMps", ...
                    norm(errorHistory(4:5, end), 2), ...
                "deadlineMissCount", sum(deadlineMiss));
        end

        function [value, initialState] = nmpcReference(time, config)
            if nargin < 2
                config = simulation.nmpcConfig();
            end
            config = simulation.nmpcSimulationConfig(config);
            [reference, initialState] = ...
                simulation.nmpcSimulationCase(config);
            step = max(0, min(config.horizon, ...
                round(double(time) / config.dt)));
            for index = 1:step
                reference = nmpc_controller.shiftReference(reference);
            end
            value = [reference.states(:); reference.commands(:)];
        end

        function output = simulinkNmpcStep(value)
            persistent warmCommands previousCost previousStage
            persistent lastTime cachedOutput hasPrevious
            config = simulation.nmpcSimulationConfig( ...
                simulation.nmpcConfig());
            referenceWidth = 6 * (config.horizon + 1) + ...
                3 * config.horizon;
            state = double(value(1:6));
            referenceValue = double(value(7:6 + referenceWidth));
            errorStart = 7 + referenceWidth;
            errorState = double(value(errorStart:errorStart + 5));
            time = double(value(errorStart + 6));
            states = reshape(referenceValue(1:6 * ...
                (config.horizon + 1)), 6, config.horizon + 1);
            commands = reshape(referenceValue(6 * ...
                (config.horizon + 1) + 1:end), 3, config.horizon);
            reference = struct("states", states, "commands", commands);
            if ~isempty(lastTime) && ~isempty(cachedOutput) && ...
                    abs(time - lastTime) <= eps
                output = cachedOutput;
                return
            end
            rewound = isempty(lastTime) || time < lastTime - eps;
            if rewound
                warmCommands = simulation.feedbackWarmStart( ...
                    state, reference, config);
                previousCost = 0;
                previousStage = 0;
                hasPrevious = false;
            end
            check = nmpc_controller.referenceAdmissible(reference, config);
            assert(check.accepted);
            warmStart = nmpc_controller.evaluatePlan( ...
                state, warmCommands, reference, config);
            if ~warmStart.feasible
                warmCommands = reference.commands;
                warmStart = nmpc_controller.evaluatePlan( ...
                    state, warmCommands, reference, config);
            end
            selected = nmpc_controller.solve( ...
                state, reference, config, warmCommands);
            if ~selected.feasible
                output = [zeros(3, 1); 0; inf(8, 1)];
                cachedOutput = output;
                lastTime = time;
                return
            end
            if hasPrevious
                lyapunovResidual = ...
                    selected.cost - previousCost + previousStage;
            else
                lyapunovResidual = 0;
            end
            expectedError = nmpc_controller.trackingError( ...
                state, reference.states(:, 1));
            if norm(expectedError - errorState, inf) > 1.0e-8
                error("simulation:simulink:errorSignal", ...
                    "Tracking error input is inconsistent with state and reference")
            end
            commandError = selected.command - reference.commands(:, 1);
            stage = errorState' * config.Q * errorState + ...
                commandError' * config.R * commandError;
            shifted = nmpc_controller.shiftPlan(selected, reference, config);
            if shifted.feasible
                warmCommands = shifted.commands;
            else
                warmCommands = selected.commands;
            end
            previousCost = selected.cost;
            previousStage = stage;
            hasPrevious = true;
            output = [selected.command; ...
                double(selected.feasible); ...
                selected.cost; stage; lyapunovResidual; ...
                selected.terminalValue / selected.terminal.rho; ...
                selected.violation; check.residual; ...
                selected.solveTimeMs; ...
                double(selected.usedFeasibleWarmStart)];
            cachedOutput = output;
            lastTime = time;
        end

        function output = simulinkCurrentReference(value)
            value = double(value(:));
            if numel(value) < 6
                error("simulation:simulink:referenceShape", ...
                    "CCA reference vector is shorter than six states")
            end
            output = value(1:6);
        end

        function output = simulinkKinematics(value)
            state = double(value(1:6));
            output = kinematics(state, state(4:6), "world");
        end

        function output = simulinkDynamics(value)
            config = simulation.nmpcSimulationConfig( ...
                simulation.nmpcConfig());
            state = double(value(1:6));
            command = double(value(7:9));
            load = double(value(10:12));
            output = dynamics(state, command, load, config);
        end

        function output = simulinkStateUpdate(value)
            config = simulation.nmpcSimulationConfig( ...
                simulation.nmpcConfig());
            state = double(value(1:6));
            derivative = double(value(7:12));
            output = state + config.dt * derivative;
            output(3) = atan2(sin(output(3)), cos(output(3)));
        end

        function output = simulinkSensorStep(value)
            config = simulation.nmpcSimulationConfig( ...
                simulation.nmpcConfig());
            state = double(value(1:6));
            time = double(value(7));
            output = sensor_model(state, time, config);
        end

        function output = simulinkEkfStep(value)
            persistent covariance lastTime cachedOutput
            config = simulation.nmpcSimulationConfig( ...
                simulation.nmpcConfig());
            previousEstimate = double(value(1:6));
            measurement = double(value(7:12));
            command = double(value(13:15));
            time = double(value(16));
            if ~isempty(lastTime) && ~isempty(cachedOutput) && ...
                    abs(time - lastTime) <= eps
                output = cachedOutput;
                return
            end
            reset = isempty(lastTime) || time < lastTime - eps || ...
                isempty(covariance);
            if reset
                covariance = config.ekfInitialCovariance;
            end
            [estimate, covariance, innovation, diagonal] = ekf_step( ...
                previousEstimate, covariance, command, measurement, config);
            output = [estimate; innovation; diagonal; trace(covariance)];
            cachedOutput = output;
            lastTime = time;
        end

        function state = simulinkInitialState(config)
            if nargin < 1
                config = simulation.nmpcConfig();
            end
            [~, state] = simulation.nmpcSimulationCase(config);
        end

        function state = simulinkInitialEstimate(config)
            if nargin < 1
                config = simulation.nmpcConfig();
            end
            config = simulation.nmpcSimulationConfig(config);
            [reference, ~] = simulation.nmpcSimulationCase(config);
            state = reference.states(:, 1);
        end

        function output = simulinkReference(time)
            output = simulation.nmpcReference(time);
        end

        function simulinkTrajectoryView(state, reference, time)
            persistent viewFigure referenceLine nmpcLine lastTime
            time = double(time);
            reset = isempty(lastTime) || time < lastTime - 1.0e-12 || ...
                isempty(viewFigure) || ~isgraphics(viewFigure);
            if reset
                visible = "off";
                if usejava("desktop")
                    visible = "on";
                end
                viewFigure = figure( ...
                    "Name", "Reference vs NMPC--Lyapunov", ...
                    "NumberTitle", "off", "Color", "w", ...
                    "Visible", visible);
                axesHandle = axes(viewFigure);
                hold(axesHandle, "on");
                referenceLine = animatedline(axesHandle, ...
                    "Color", [0.15, 0.15, 0.15], ...
                    "LineStyle", "--", "LineWidth", 1.6, ...
                    "DisplayName", "Reference");
                nmpcLine = animatedline(axesHandle, ...
                    "Color", [0.00, 0.45, 0.74], ...
                    "LineWidth", 1.8, ...
                    "DisplayName", "NMPC--Lyapunov");
                axis(axesHandle, "equal");
                grid(axesHandle, "on");
                xlabel(axesHandle, "x (m)");
                ylabel(axesHandle, "y (m)");
                legend(axesHandle, "Location", "best");
                lastTime = -inf;
            end
            if time <= lastTime + 1.0e-12
                return
            end
            addpoints(referenceLine, double(reference(1)), ...
                double(reference(2)));
            addpoints(nmpcLine, double(state(1)), double(state(2)));
            drawnow limitrate
            lastTime = time;
        end

        function config = nmpcSimulationConfig(config)
            config.stateLower = [-2; -2; -pi; -2; -2; -3];
            config.stateUpper = [2; 2; pi; 2; 2; 3];
            config.solveDeadlineMs = 10000;
        end

        function [reference, initialState, errorState] = ...
                nmpcSimulationCase(config)
            reference = nmpc_controller.referenceFromPath( ...
                zeros(6, 1), [0, 0; 0.15, 0], config);
            terminal = nmpc_controller.terminalDesign( ...
                reference.states(:, end), config);
            direction = [1; -0.6; 0; 0.4; -0.2; 0];
            direction = direction / sqrt( ...
                direction' * terminal.P * direction);
            errorState = 10 * sqrt(terminal.rho) * direction;
            initialState = reference.states(:, 1) + errorState;
        end

        function commands = feedbackWarmStart(state, reference, config)
            terminal = nmpc_controller.terminalDesign( ...
                reference.states(:, end), config);
            commands = zeros(3, config.horizon);
            cursor = state(:);
            for index = 1:config.horizon
                errorState = nmpc_controller.trackingError( ...
                    cursor, reference.states(:, index));
                commands(:, index) = reference.commands(:, index) + ...
                    terminal.K * errorState;
                cursor = position_step( ...
                    cursor, commands(:, index), config.dt, ...
                    config.velocityTimeConstant);
            end
        end
    end
end
