function speeds = wheel_speeds(command, wheelRadius, halfLength, halfWidth)
arm = halfLength + halfWidth;
mixer = [1, -1, -arm; ...
         1,  1,  arm; ...
         1,  1, -arm; ...
         1, -1,  arm] / wheelRadius;
speeds = mixer * double(command(:));
end
